version: '2'
services:

  devenv:
    command: ["tail", "-f", "/dev/null"]
    image: devenv:latest
  #-----------------------
  # 以下追加
    volumes:
      - ./data:/data
    environment:
      TZ: Asia/Tokyo
